name = "Welfare - Universal Health Care"
version = 3
copyright = "GNU GPLv3"
description = "Donald Trump defeated Soros and provided us all with GREAT HUGE AMERICAN Health Care.\nT1 Eng: 1 Mass 10 Energy, T2 Eng: 2 Mass 25 Energy, T3 Eng: 3 Mass 1000 Energy, Support Commander: 5 Mass 2000 Energy, Main Commander: 200 Mass 10,000 Energy"
author = "Screap+SageTheWizard"
uid = "69c700e2-fd42-11eb-9a03-0242ac130003"
icon = "/mods/Welfare - Universal Health Care/supremacist_commander.png"
exclusive = false
ui_only = false
selectable = true
enabled = true
requires = { }
requiresNames = { }
conflicts = { }
before = { }
after = { }